// <auto-generated />
using CandidateProfileSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CandidateProfileSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250326121249_SeedCandidatesAndTechnologies")]
    partial class SeedCandidatesAndTechnologies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CandidateProfileSystem.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DegreeCompletionYear")
                        .HasColumnType("int");

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "9878",
                            DegreeCompletionYear = 2025,
                            DegreeName = "Btech",
                            Email = "rahulg@gmail.com",
                            Name = "Rahul",
                            TechnologyId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "9879",
                            DegreeCompletionYear = 2025,
                            DegreeName = "Btech",
                            Email = "sky@gmail.com",
                            Name = "Sky",
                            TechnologyId = 2
                        });
                });

            modelBuilder.Entity("CandidateProfileSystem.Models.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TechnologyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TechnologyName = "Java 1"
                        },
                        new
                        {
                            Id = 2,
                            TechnologyName = "C#"
                        });
                });

            modelBuilder.Entity("CandidateProfileSystem.Models.Candidate", b =>
                {
                    b.HasOne("CandidateProfileSystem.Models.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId");

                    b.Navigation("Technology");
                });
#pragma warning restore 612, 618
        }
    }
}
